#!/bin/bash

#Bash script that runs java class files

if [ "$1" == "--help" ]; then
	echo "Usage: $0 [ path/to/java_class_file ] [ path/to/xml_file ]"
	echo "e.g. $0 testpackage/TestClass /c/users/Test.xml"
	exit 0
fi

if [ $# -ne 2 ]; then
	echo "Usage: $0 [ path/to/java_class_file ] [ path/to/xml_file ]"
	echo "Type $0 --help for more information"
	exit 1
fi

MASTER=$(git rev-parse --show-toplevel | sed 's_^C\:_/c_g')
if [ "$OSTYPE"  == "linux-gnu" ]; then
    MASTER=$(git rev-parse --show-toplevel | sed 's/^C\:/c/g')
fi
CLASSPATH=$MASTER"/ROOT/WEB-INF/classes"
LIB=$MASTER"/ROOT/WEB-INF/lib/mysql-connector-java-5.1.41-bin.jar"
class_file=$1".class"
xml_path=$2

#check if file does not exist
#if [ ! -f "$CLASSPATH/$class_file" ]; then
#	echo "file not found: $CLASSPATH/$class_file"
#	exit 1
#fi


printf "all:\n\tjava -cp $CLASSPATH:$LIB $1 $2" > makefile
make --quiet
rm makefile
