#!/bin/bash


# Runs any compiled java class file in the Tomcat Webapps workspace
# USAGE: unitTest [ filename.class ]
# e.g. unitTest CalculatorTest.class

if [ "$1" == "--help" ] && [ $# -eq 1 ]; then
	echo "Usage: unitTest [ filename.class ]"
	echo "Description: Runs any compiled java class file in the Tomcat Webapps workspace"
	echo "e.g. unitTest CalculatorTest.class"
	exit 0
fi

if [ $# -ne 1 ]; then
	echo "Usage: unitTest [ filename.class ]"
	echo "Type unitTest --help for more information"
	exit 1
fi

master_path="/"$(git rev-parse --show-toplevel | sed 's/^C\:/c/g')
class_path="ROOT/WEB-INF/classes"
class_name="$1"
#trim .class extension from file
ext=$(echo $class_name | sed 's/\(.*\)\./\1:/' | cut -f2 -d":")

if [ "$ext" != "class" ]; then
	echo "$class_name is not a '.class' file"
	exit 1
fi

#if file does not exist in specified filepath
if [ ! -f "$master_path/$class_path/$class_name" ]; then
	echo "file not found: $master_path/$class_path/$class_name"
	exit 1
fi

#if file exists, create a makefile to run java class file
lib_path="ROOT/WEB-INF/lib"

printf "all:\n\tjava -cp $master_path/$class_path" > java2Makefile
for file in $(ls $master_path/$lib_path/*.jar); do
	printf ":$file" >> java2Makefile
done

#grab class name without extension .class
class=$(echo $class_name | sed 's/\(.*\)\./\1:/' | cut -f1 -d":")

#junit main class for testing
printf " org.junit.runner.JUnitCore $class" >> java2Makefile

#execute makefile
make -f java2Makefile --silent
rm java2Makefile
